block.settings.redfin_connect_block:
  type: block_settings
  label: 'Redfin Connect Block'
  mapping:
    telephone:
      type: string
      label: 'Telephone Number'
    email:
      type: string
      label: 'Email Address'
    address_line1:
      type: string
      label: 'Address Line 1'
    address_line2:
      type: string
      label: 'Address Line 2'
    linkedin:
      type: string
      label: 'LinkedId'
    facebook:
      type: string
      label: 'Facebook'
    twitter:
      type: string
      label: 'Twitter'
    instagram:
      type: string
      label: 'Instagram'